version: '2'

services:
    php:
        build: ./php
        container_name: php
        volumes_from:
            - source
        ports:
            - '9000:9000'
        links:
            - mysql
            - memcached
        networks:
            - bitrix
        restart: always
    # apache:
    #     build: ./apache
    #     container_name: apache
    #     depends_on:
    #         - source
    #     volumes_from:
    #         - source
    #     ports:
    #         - '80:80'
    #         - '443:443'
    #     links:
    #         - php
    #     networks:
    #         - bitrix
    #     restart: always
    nginx:
        build: ./nginx
        container_name: nginx
        volumes_from:
            - source
        ports:
            - '80:80'
            - '443:443'
        links:
            - php
        networks:
            - bitrix
        restart: always
    mysql:
        build: ./mysql
        container_name: mysql
        volumes_from:
            - source
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: bitrix
            MYSQL_USER: bitrix
            MYSQL_PASSWORD: 123
            MYSQL_ROOT_PASSWORD: 123
        networks:
            - bitrix
        restart: always
    memcached:
        image: memcached:1.5-alpine
        container_name: memcached
        volumes_from:
            - source
        ports:
            - '11211:11211'
        networks:
            - bitrix
        restart: always
    source:
        image: alpine:latest
        container_name: source
        volumes:
            - ./logs/nginx:/var/log/nginx
            - ./logs/php:/var/log/php
            - ./logs/mysql:/var/log/mysql
            - ./logs/memcached:/var/log/memcached
            - ./data/mysql:/var/lib/mysql
            - ./data/memcached:/var/lib/memcached
            - /home/nvadim/sites/shmel:/var/www/bitrix
            - /etc/localtime:/etc/localtime/:ro
        networks:
            - bitrix
networks:
    bitrix:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.100.0.0/24
